### ISSUE TITLE
Special chars like àèìòù are not passed correctly in email body ('content')

### ISSUE THREAD

**Issue by realwahl** [pepipost/pepipost-sdk-php#9]
I'm trying to send an email in italian, so it contains characters like àèìòù. I used the sample code, only that I added the string àèìòù to 'subject' and 'content'. The email arrives with the correct subject, but the content is "this ����� mail is sent via PHP SDK" instead of "this àèìòù mail is sent via PHP SDK". What can I do?

**Comment by ivikramsahu** [comment]
Hi @realwahl,
 Please pass rawurlencoded string in order to avoid junk characters. After rawurlencode it will look something like this **'"subject":"Pepipost%20test%20%C3%A0%C3%A8%C3%AC%C3%B2%C3%B9'"** For now the particular string "àèìòù" is in such format **"subject":"Pepipost test \u00e0\u00e8\u00ec\u00f2\u00f9"** which is junk character.
Vikram | [pepipost.com](https://pepipost.com)

**Comment by realwahl** [comment]
I managed to make it work using this workaround inside my code.

From a logical point of view thought, your library should call this function before sending it in GET or POST. On my side, I am passing an array to sendJson() and it should not be encoded in any way. The texts are UTF-8 as requested. It is the class that need to do the encoding, as it needs to send it in GET or post.

**Comment by ivikramsahu** [comment]
Thanks @realwahl  it is a valuable suggestion which will surely help us alot. 
we will be updating our sdk in our upcoming release soon 
Regards,
Vikram |  [pepipost.com](https://pepipost.com)

**Comment by tazilios** [comment]
Hello,

The issue is still present and is definitely a showstopper for us (as it will be for the majority or the european customers).
Any chance to get this fixed before I move to another supplier?

**Comment by ivikramsahu** [comment]
Hey @tazilios, 
will check and update you on the same.
Thanks.

**Comment by ivikramsahu** [comment]
Hello @tazilios,
UTF8 character support has been added in the SDK, please check and let me know if in case of query.
you can check the [simple-usage.php](https://github.com/pepipost/pepipost-sdk-php/blob/master/simple-usage.php)
Thanks.

**Comment by tazilios** [comment]
Hi Snipperbytes !

I'm actually using the API so I assume that it is the latest version...
Anything else I can double check?

Cheers

**Comment by tazilios** [comment]
By the way, I also tested the encodeURIComponent function to rawurlencode the mail content but the special character are still wrong in the received email:

Pr�sentation � l'�quipe B (15-07-2020) * Nouveau point R�alis� par aBoard �

**Comment by tazilios** [comment]
I did upgrade to the latest version of the node.js package (5.0) but no change...
Actually, I now see that you made the change in the PHP SDK.
May I ask you to do the same change in the nodejs one?

**Comment by ivikramsahu** [comment]
Hey @tazilios,

Which SDK are you using PHP or node? Or both?
I will make sure it gets fixed in other SDK too, but that will take time... so I appreciate your patience.

Cheers

**Comment by tazilios** [comment]
Thanks for coming back to me.
I'm using the node one, if you can give it a priority, that would be great !

Cheers

**Comment by tazilios** [comment]
Hi,

It's been a month, any update on this?

Cheers

**Comment by ivikramsahu** [comment]
Hey @tazilios 

We are already working on this part with few more feature addition in pipeline and planning to release probably by this week (5th August 2020).
so I appreciate your patience.

Cheers

**Comment by tazilios** [comment]
Hello,

Any update for me?
My pilot customers are complaining about it and I'd like to give them a date.

Cheers

**Comment by ivikramsahu** [comment]
Hey @tazilios,

The [GitHub repo](https://github.com/pepipost/pepipost-sdk-nodejs) has been updated.. please go through the [code](https://github.com/pepipost/pepipost-sdk-nodejs/blob/master/advance-usage.js)

Cheers.

**Comment by tazilios** [comment]
Hello,

Thanks for informing me, I tested with the new package but....
![image](https://user-images.githubusercontent.com/17636261/90676207-ef206380-e25b-11ea-9730-f9fd5e026e6c.png)

...as you can see, the email still contains those error symbols in stead of the original ones.

Did you test the code with special characters like é è ? 

Cheers

**Comment by ivikramsahu** [comment]
yeah, we tested @tazilios let me check it again and revert you with an update 

thanks..
